mongodb:
   image: mongo
   container_name: mongo
   ports:
      - 27017
   hostname: mongo
   volumes:
       - $HOME/mongo/data/db:/data/db

cardsappserver:
   image: cardsapp:0.3
   container_name: cardapps
   ports:
     - 8080:8080
   hostname: cardapps
   links:
      - mongodb:mongodb

